apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: users
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: tasks
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      targetPort: 80
